AxaFailProof/Models/Mushroom.cs
using System;
using System.Collections.Generic;

namespace AxaFailProof.Models
{
    public partial class Mushroom
    {
        public int MushroomID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}

AxaFailProof/Areas/Admin/Controllers/MushroomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AxaFailProof.Models;

namespace AxaFailProof.Areas.Admin.Controllers
{
    //[Authorize]
    public class MushroomController : Controller
    {
        private AxaFailProofContext db = new AxaFailProofContext();

        //
        // GET: /Admin/Mushroom/

        public ViewResult Index()
        {
            return View(db.Mushrooms.OrderByDescending(m=> m.DateCreated).ToList());
        }

        //
        // GET: /Admin/Mushroom/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Admin/Mushroom/Create
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Mushroom mushroom)
        {
            if (ModelState.IsValid)
            {
                mushroom.Status = true;
                mushroom.DateCreated = DateTime.Now;
                db.Mushrooms.Add(mushroom);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(mushroom);
        }
        
        //
        // GET: /Admin/Mushroom/Edit/5
 
        public ActionResult Edit(int id)
        {
            Mushroom mushroom = db.Mushrooms.Find(id);
            return View(mushroom);
        }

        //
        // POST: /Admin/Mushroom/Edit/5
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Edit(Mushroom mushroom)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mushroom).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mushroom);
        }

        //
        // POST: /Admin/Mushroom/Delete/5

        //[HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Mushroom mushroom = db.Mushrooms.Find(id);
            db.Mushrooms.Remove(mushroom);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Status(int id)
        {
            Mushroom mushroom = db.Mushrooms.Find(id);
            if (mushroom.Status == false)
            {
                mushroom.Status = true;
            }
            else
            {
                mushroom.Status = false;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AxaFailProof/Areas/Admin/Views/Mushroom/Create.cshtml
@model AxaFailProof.Models.Mushroom

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout3.cshtml";
    ViewBag.Title = "Create Mushroom";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div class="panel-header">
    <h3>Mushroom : Create </h3>
</div>
@using (Html.BeginForm("Create", "Mushroom", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="panel-body">
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Title)</label>
            <div class="controls">
                @Html.TextBoxFor(model => model.Title, new { @class = "input-text", style = "width:320px;" })<br />
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Body)</label>
            <div class="controls">
                @Html.TextAreaFor(model => model.Body, new { @class = "input-text"})<br />
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>
    </fieldset>

    <script type="text/javascript">
        CKEDITOR.config.allowedContent = true;
        CKEDITOR.replace('Body');
    </script>

</div>
<div class="panel-footer">
    <div class="panel-button">
        <input type="button" class="btn-submit panel-button-right" value="Back to List" onclick="location.href='@Url.Action("Index")';" />
        <input type="submit" class="btn-submit panel-button-right" value="Create" />
        <div class="clearboth"></div>
    </div>
</div>
}

AxaFailProof/Areas/Admin/Views/Mushroom/Edit.cshtml
@model AxaFailProof.Models.Mushroom

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout3.cshtml";
    ViewBag.Title = "Edit Mushroom";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div class="panel-header">
    <h3>Mushroom : Edit </h3>
</div>
@using (Html.BeginForm("Edit", "Mushroom", FormMethod.Post))
{
<div class="panel-body">
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.MushroomID)
    @Html.HiddenFor(model => model.DateCreated)
    @Html.HiddenFor(model => model.Status)
    <fieldset>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Title)</label>
            <div class="controls">
                @Html.TextBoxFor(model => model.Title, new { @class = "input-text", style = "width:320px;" })<br />
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Body)</label>
            <div class="controls">
                @Html.TextAreaFor(model => model.Body, new { @class = "input-text"})<br />
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>
    </fieldset>

    <script type="text/javascript">
        CKEDITOR.config.allowedContent = true;
        CKEDITOR.replace('Body');
    </script>

</div>
<div class="panel-footer">
    <div class="panel-button">
        <input type="button" class="btn-submit panel-button-right" value="Back to List" onclick="location.href='@Url.Action("Index")';" />
        <input type="submit" class="btn-submit panel-button-right" value="Save" />
        <div class="clearboth"></div>
    </div>
</div>
}

AxaFailProof/Areas/Admin/Views/Mushroom/Index.cshtml
@model IEnumerable<AxaFailProof.Models.Mushroom>
@{
    ViewBag.Title = "Mushroom";
}

<div class="panel-header">
    <h3>Mushroom</h3>
</div>

<div class="panel-body">

<div><input type="button" class="btn-submit panel-button-right" value="Create New" onclick="location.href='@Url.Action("Create")';" /></div>

<table class="table table-hover">
    <thead>
    <tr>
        <th>
            Title
        </th>
        <th>
            DateCreated
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>

@foreach (var item in Model) {
    var image = "";
    if (item.Status==true)
    {
        image = "~/Areas/Admin/Content/images/accept.png";
    }
    else
    {
        image = "~/Areas/Admin/Content/images/cross.png";
    }    
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
            <td width="28%" align="right" height="25" style="padding-left:5px;" nowrap="nowrap">
            &nbsp;<a href="@Url.Action("Edit", "Mushroom", new { id = item.MushroomID })"><img src="@Url.Content("~/Areas/Admin/Content/images/page_edit.png")" title="Edit" alt"Edit" width="16" height="16" align="absmiddle" border="0"/></a> 
            &nbsp;<a onclick="deleteme('@Url.Action("DeleteConfirmed", "Mushroom", new { id = item.MushroomID })')" style="cursor:pointer;"><img src="@Url.Content("~/Areas/Admin/Content/images/delete.png")" width="16" title="Delete" alt="Delete" height="16" align="absmiddle" border="0"/></a> 
            &nbsp;<a href="@Url.Action("Status", "Mushroom", new { id = item.MushroomID })"><img src="@Url.Content(@image)" width="16" title="Status" alt="Status" height="16" align="absmiddle" border="0"/></a>
            &nbsp;&nbsp; 
        </td>
    </tr>
}
</tbody>
</table>
</div>
<div class="clearboth"></div>
<div class="panel-footer"></div>