AxaFailProof/Models/ContactU.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AxaFailProof.Models
{
    public partial class ContactU
    {
        public int ContactID { get; set; }
        [Required(ErrorMessage = "Please enter your name.")]
        public string Name { get; set; }
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid email address format.")]
        [Required(ErrorMessage = "Please enter your email address.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your message.")]
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}

AxaFailProof/Areas/Admin/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AxaFailProof.Models;
using AxaFailProof.ExcelUtilities;
using System.IO;

namespace AxaFailProof.Areas.Admin.Controllers
{
    [Authorize]
    public class ContactUsController : Controller
    {
        private AxaFailProofContext db = new AxaFailProofContext();

        //
        // GET: /Admin/ContactUs/

        public ViewResult Index()
        {
            return View(db.ContactUs.ToList());
        }

        //
        // GET: /Admin/ContactUs/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Admin/ContactUs/Create

        [HttpPost]
        public ActionResult Create(ContactU contactu)
        {
            if (ModelState.IsValid)
            {
                contactu.DateCreated = DateTime.Now;
                db.ContactUs.Add(contactu);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(contactu);
        }
        
        //
        // GET: /Admin/ContactUs/Edit/5
 
        public ActionResult Edit(int id)
        {
            ContactU contactu = db.ContactUs.Find(id);
            return View(contactu);
        }

        //
        // POST: /Admin/ContactUs/Edit/5

        [HttpPost]
        public ActionResult Edit(ContactU contactu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contactu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contactu);
        }

        //
        // POST: /Admin/ContactUs/Delete/5

        //[HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            ContactU contactu = db.ContactUs.Find(id);
            db.ContactUs.Remove(contactu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public void DownloadExl()
        {
            var newsletter = new DataTable();
            newsletter.Columns.Add(new DataColumn("Name", Type.GetType("System.String")));
            newsletter.Columns.Add(new DataColumn("Email", Type.GetType("System.String")));
            newsletter.Columns.Add(new DataColumn("Message", Type.GetType("System.String")));
            newsletter.Columns.Add(new DataColumn("DateCreated", Type.GetType("System.String")));

            var registerduser = db.ContactUs.OrderByDescending(n => n.DateCreated);
            foreach (var item in registerduser)
            {
                object[] data = new Object[4];
                data[0] = item.Name;
                data[1] = item.Email;
                data[2] = item.Message;
                data[3] = item.DateCreated.ToString("yyyy-MM-dd");
                newsletter.Rows.Add(data);
            }

            MemoryStream stream = ExcelUtility.GetExcel(newsletter);

            var filename = DateTime.Now + "_ContactUs.xlsx";
            var contenttype = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.Clear();
            Response.ContentType = contenttype;
            Response.AddHeader("content-disposition", "attachment;filename=" + filename);
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.BinaryWrite(stream.ToArray());
            Response.End();
        }            


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AxaFailProof/Areas/Admin/Views/ContactUs/Create.cshtml
@model AxaFailProof.Models.ContactU

@{
    ViewBag.Title = "Contact Us";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div class="panel-header">
    <h3>Contact Us : Create </h3>
</div>

@using (Html.BeginForm("Create", "ContactUs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="panel-body">
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Name)</label>
            <div class="controls">
                @Html.TextBoxFor(model => model.Name, new { @class = "input-text", style = "width:320px;" })<br />
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Email)</label>
            <div class="controls">
                @Html.TextBoxFor(model => model.Email, new { @class = "input-text", style = "width:320px;" })<br />
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Message)</label>
            <div class="controls">
                @Html.TextAreaFor(model => model.Message, new { @class = "input-text", style = "width:320px;" })<br />
                @Html.ValidationMessageFor(model => model.Message)
            </div>
        </div>
    </fieldset>
</div>
<div class="panel-footer">
    <div class="panel-button">
        <input type="button" class="btn-submit panel-button-right" value="Back to List" onclick="location.href='@Url.Action("Index")';" />
        <input type="submit" class="btn-submit panel-button-right" value="Create" />
        <div class="clearboth"></div>
    </div>
</div>
}

AxaFailProof/Areas/Admin/Views/ContactUs/Edit.cshtml
@model AxaFailProof.Models.ContactU

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>ContactU</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ContactID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ContactID)
            @Html.ValidationMessageFor(model => model.ContactID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Message)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Message)
            @Html.ValidationMessageFor(model => model.Message)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AxaFailProof/Areas/Admin/Views/ContactUs/Index.cshtml
@model IEnumerable<AxaFailProof.Models.ContactU>

@{
    ViewBag.Title = "Contact Us";
}
<div class="panel-header">
    <h3>Contact Us List</h3>
</div>

<div class="panel-body">
<input type="button" class="btn-submit panel-button-right" value="Download Excel File" onclick="location.href='@Url.Action("DownloadExl")';" />
<table class="table table-hover">
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Email
        </th>
        <th>
            Message
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
            <td align="right" height="25" style="padding-left:5px;" nowrap="nowrap">
            &nbsp;<a onclick="deleteme('@Url.Action("DeleteConfirmed", "ContactUs", new { id = item.ContactID })')" style="cursor:pointer;"><img src="@Url.Content("~/Areas/Admin/Content/images/delete.png")" width="16" title="Delete" alt="Delete" height="16" align="absmiddle" border="0"/></a> 
            &nbsp;&nbsp; 
        </td>
    </tr>
}
</tbody>
</table>
</div>
<div class="clearboth"></div>
<div class="panel-footer"></div>