AxaFailProof/Models/FailProofing.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AxaFailProof.Models
{
    public partial class FailProofing
    {
        public int FailID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LocationCity { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}

AxaFailProof/Areas/Admin/Controllers/FailProofingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AxaFailProof.Models;

namespace AxaFailProof.Areas.Admin.Controllers
{
    [Authorize]
    public class FailProofingController : Controller
    {
        private AxaFailProofContext db = new AxaFailProofContext();

        //
        // GET: /Admin/FailProofing/

        public ViewResult Index()
        {
            return View(db.FailProofing.ToList());
        }

        //
        // GET: /Admin/FailProofing/Details/5

        public ViewResult Details(int id)
        {
            FailProofing failproofing = db.FailProofing.Find(id);
            return View(failproofing);
        }

        //
        // POST: /Admin/FailProofing/Delete/5

        //[HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            FailProofing failproofing = db.FailProofing.Find(id);
            db.FailProofing.Remove(failproofing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AxaFailProof/Areas/Admin/Views/FailProofing/Index.cshtml
@model IEnumerable<AxaFailProof.Models.FailProofing>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout3.cshtml";
    ViewBag.Title = "Fail Proofing";
}
<div class="panel-header">
    <h3>Fail Proofing</h3>
</div>

<div class="panel-body">
<table class="table table-hover">
    <thead>
    <tr>
        <th>
            FirstName
        </th>
        <th>
            LastName
        </th>
        <th>
            Location
        </th>
        <th>
            ContactNumber
        </th>
        <th>
            Email
        </th>
        <th>
            DateCreated
        </th>
        <th></th>
    </tr>
       </thead>
    <tbody>
@foreach (var item in Model) {
    var image = "";
    if (item.Status == true)
    {
        image = "~/Areas/Admin/Content/images/accept.png";
    }
    else
    {
        image = "~/Areas/Admin/Content/images/cross.png";
    }      
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocationCity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td align="right" height="25" style="padding-left:5px;" nowrap="nowrap">
            &nbsp;<a onclick="deleteme('@Url.Action("DeleteConfirmed", "FailProofing", new { id = item.FailID })')" style="cursor:pointer;"><img src="@Url.Content("~/Areas/Admin/Content/images/delete.png")" width="16" title="Delete" alt="Delete" height="16" align="absmiddle" border="0"/></a> 
            &nbsp;&nbsp; 
        </td>

    </tr>
}
</tbody>
</table>
</div>
<div class="clearboth"></div>
<div class="panel-footer"></div>