AxaFailProof/Models/StaticPage.cs
using System;
using System.Collections.Generic;

namespace AxaFailProof.Models
{
    public partial class StaticPage
    {
        public int StaticID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string MetaKeyWords { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}

AxaFailProof/Areas/Admin/Controllers/StaticPageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AxaFailProof.Models;

namespace AxaFailProof.Areas.Admin.Controllers
{
    [Authorize]
    public class StaticPageController : Controller
    {
        private AxaFailProofContext db = new AxaFailProofContext();

        //
        // GET: /Admin/StaticPage/

        public ViewResult Index()
        {
            return View(db.StaticPages.OrderByDescending(s => s.DateCreated).ToList());
        }

        //
        // GET: /Admin/StaticPage/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Admin/StaticPage/Create
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(StaticPage staticpage)
        {
            if (ModelState.IsValid)
            {
                staticpage.Status = true;
                staticpage.DateCreated = DateTime.Now;
                db.StaticPages.Add(staticpage);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(staticpage);
        }
        
        //
        // GET: /Admin/StaticPage/Edit/5
 
        public ActionResult Edit(int id)
        {
            StaticPage staticpage = db.StaticPages.Find(id);
            return View(staticpage);
        }

        //
        // POST: /Admin/StaticPage/Edit/5
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Edit(StaticPage staticpage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staticpage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(staticpage);
        }

        //
        // POST: /Admin/StaticPage/Delete/5

        //[HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            StaticPage staticpage = db.StaticPages.Find(id);
            db.StaticPages.Remove(staticpage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Status(int id)
        {
            StaticPage staticpage = db.StaticPages.Find(id);
            if (staticpage.Status== false)
            {
                staticpage.Status = true;
            }
            else
            {
                staticpage.Status = false;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AxaFailProof/Areas/Admin/Views/StaticPage/Create.cshtml
@model AxaFailProof.Models.StaticPage

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout3.cshtml";
    ViewBag.Title = "Create Static Page";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div class="panel-header">
    <h3>Static Page : Create </h3>
</div>
@using (Html.BeginForm("Create", "StaticPage", FormMethod.Post, new { enctype = "multipart/form-data" })){
<div class="panel-body">
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Title)</label>
            <div class="controls">
                @Html.TextBoxFor(model => model.Title, new { @class = "input-text", style = "width:420px;" })<br />
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.MetaKeyWords)</label>
            <div class="controls">
                @Html.TextAreaFor(model => model.MetaKeyWords, new { @class = "input-text", style = "width:420px;" })<br />
                @Html.ValidationMessageFor(model => model.MetaKeyWords)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.MetaDescription)</label>
            <div class="controls">
                @Html.TextAreaFor(model => model.MetaDescription, new { @class = "input-text", style = "width:420px;" })<br />
                @Html.ValidationMessageFor(model => model.MetaDescription)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Body)</label>
            <div class="controls">
                @Html.TextAreaFor(model => model.Body, new { @class = "input-text"})<br />
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>
    </fieldset>

    <script type="text/javascript">
        CKEDITOR.replace('Body');
    </script>

</div>
<div class="panel-footer">
    <div class="panel-button">
        <input type="button" class="btn-submit panel-button-right" value="Back to List" onclick="location.href='@Url.Action("Index")';" />
        <input type="submit" class="btn-submit panel-button-right" value="Create" />
        <div class="clearboth"></div>
    </div>
</div>
}

AxaFailProof/Areas/Admin/Views/StaticPage/Edit.cshtml
@model AxaFailProof.Models.StaticPage
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout3.cshtml";
    ViewBag.Title = "Edit Static Page";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div class="panel-header">
    <h3>Static Page : Edit </h3>
</div>
@using (Html.BeginForm("Edit", "StaticPage", FormMethod.Post)) {
<div class="panel-body">
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.StaticID)
    @Html.HiddenFor(model => model.DateCreated)
    @Html.HiddenFor(model => model.Status)
    <fieldset>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Title)</label>
            <div class="controls">
                @Html.TextBoxFor(model => model.Title, new { @class = "input-text", style = "width:320px;" })<br />
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.MetaKeyWords)</label>
            <div class="controls">
                @Html.TextAreaFor(model => model.MetaKeyWords, new { @class = "input-text", style = "width:420px;" })<br />
                @Html.ValidationMessageFor(model => model.MetaKeyWords)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.MetaDescription)</label>
            <div class="controls">
                @Html.TextAreaFor(model => model.MetaDescription, new { @class = "input-text", style = "width:420px;" })<br />
                @Html.ValidationMessageFor(model => model.MetaDescription)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Html.LabelFor(model => model.Body)</label>
            <div class="controls">
                @Html.TextAreaFor(model => model.Body, new { @class = "input-text"})<br />
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>
    </fieldset>

    <script type="text/javascript">
        CKEDITOR.config.allowedContent = true;
        CKEDITOR.replace('Body');
    </script>

</div>
<div class="panel-footer">
    <div class="panel-button">
        <input type="button" class="btn-submit panel-button-right" value="Back to List" onclick="location.href='@Url.Action("Index")';" />
        <input type="submit" class="btn-submit panel-button-right" value="Save" />
        <div class="clearboth"></div>
    </div>
</div>
}

AxaFailProof/Areas/Admin/Views/StaticPage/Index.cshtml
@model IEnumerable<AxaFailProof.Models.StaticPage>

@{
    ViewBag.Title = "Static Page";
}

<div class="panel-header">
    <h3>Static Page</h3>
</div>

<div class="panel-body">

<div><input type="button" class="btn-submit panel-button-right" value="Create New" onclick="location.href='@Url.Action("Create")';" /></div>

<table class="table table-hover">
    <thead>
    <tr>
        <th>
            Title
        </th>
        <th>
            DateCreated
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    var image = "";
    if (item.Status==true)
    {
        image = "~/Areas/Admin/Content/images/accept.png";
    }
    else
    {
        image = "~/Areas/Admin/Content/images/cross.png";
    }    
    
    
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
            

            <td width="28%" align="right" height="25" style="padding-left:5px;" nowrap="nowrap">
            &nbsp;<a href="@Url.Action("Edit", "StaticPage", new { id = item.StaticID })"><img src="@Url.Content("~/Areas/Admin/Content/images/page_edit.png")" title="Edit" alt"Edit" width="16" height="16" align="absmiddle" border="0"/></a> 
            &nbsp;<a onclick="deleteme('@Url.Action("DeleteConfirmed", "StaticPage", new { id = item.StaticID })')" style="cursor:pointer;"><img src="@Url.Content("~/Areas/Admin/Content/images/delete.png")" width="16" title="Delete" alt="Delete" height="16" align="absmiddle" border="0"/></a> 
            &nbsp;<a href="@Url.Action("Status", "StaticPage", new { id = item.StaticID })"><img src="@Url.Content(@image)" width="16" title="Status" alt="Status" height="16" align="absmiddle" border="0"/></a>
            &nbsp;&nbsp; </td>
    </tr>
}
</tbody>
</table>
</div>
<div class="clearboth"></div>
<div class="panel-footer"></div>